esphome:
  name: tbd_v1
  comment: "TBD basic Eurorack module"
    
esp32:
  variant: esp32
  board: esp-wrover-kit
  framework: 
    type: esp-idf
    version: latest

external_components:
  - source: ${TBD_ROOT}/components/core
  - source: ${TBD_ROOT}/components/audio
  - source: ${TBD_ROOT}/components/control_inputs
  - source: ${TBD_ROOT}/components/vendor

ota:
  platform: esphome
  password: !secret api_password
    
wifi:
  ssid: !secret ssid
  password: !secret wifi_password


tbd_adc:
  calibration: false

tbd_wm8xxx:
  type: wm8731
  pins:
    spi:
      sclk: 12
      mosi: 13
      miso: 0
      cs: 4
    i2s:
      bclk: 21
      ws: 19
      dout: 22
      din: 27

tbd_indicator:
  pins:
    red: 14
    green: 15
    blue: 18


tbd_test_plugins:

tbd_audio:

tbd_api:
