esphome:
  name: tbdbba2
    
esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework: 
    type: esp-idf
    version: latest

# external_components:
#   - source: ${TBD_ROOT}/components/core
#   - source: ${TBD_ROOT}/components/api
#   - source: ${TBD_ROOT}/components/audio
#   - source: ${TBD_ROOT}/components/control_inputs
#   - source: ${TBD_ROOT}/components/vendor

ota:
  platform: esphome
  password: !secret api_password
    
wifi:
  ssid: !secret ssid
  password: !secret wifi_password


tbd_aic3254:
  pins:
    i2c:
      sda: 41
      scl: 20
    i2s:
      mclk: 39
      bclk: 45
      ws: 1
      dout: 2
      din: 21

tbd_midi:
  inputs:
    - UART
    - USB

tbd_indicator:
  pin: 38

tbd_builtin_sounds:

tbd_test_plugins:

tbd_audio:

tbd_websocket:
