esphome:
    name: tbddesktop

host:
  mac_address: "06:35:69:ab:f6:79"

external_components:
  - source: /home/mlee/code/tbd_example/components

# external_components:
#   - source: ${TBD_ROOT}/components/core
#   - source: ${TBD_ROOT}/components/audio
#   - source: ${TBD_ROOT}/components/control_inputs
#   - source: ${TBD_ROOT}/components/vendor

tbd_rt_midi:

tbd_rt_audio:

#tbd_indicator:

#tbd_builtin_sounds:
#   whitelist:
#     - void
#     - cstrip
#     - spacefx


tbd_test_plugins:

#tbd_audio:

tbd_sound_processor:

tbd_example:
  
tbd_api:

tbd_websocket:

uart:
  id: host_uart
  baud_rate: 9600
  port: "/dev/ttyUSB0"

tbd_uart:
  uart_id: host_uart
