name: build tbd firmware

on:
  workflow_call:
    inputs:
      tbd-platform:
        required: true
        type: string

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup build container
        run: ls -1 tools/docker/ci_builder.Dockerfile && docker build -t tbd_ci_builder -f tools/docker/ci_builder.Dockerfile $PWD

      - name: build firmware
        run: docker run -it -v$PWD:/code -v$PWD/build:/build tbd_ci_builder ${{ inputs.tbd-platform }}

      - name: upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tbd_${{ inputs.tbd-platform }}
          path: |
            build/${{ inputs.tbd-platform }}/.pioenvs/${{ inputs.tbd-platform }}/program
          overwrite: true
