name: build tbd firmware

on:
  workflow_call:
    inputs:
      tbd-platform:
        required: true
        type: string

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup build container
        run: ls -1 tools/docker/build.Dockerfile && docker build -t tbd_firmware -f tools/docker/build.Dockerfile $PWD

      - name: build firmware
        run: docker run --user "$(id -u):$(id -g)" -v $PWD:/code tbd_firmware ${{ inputs.tbd-platform }} configure bin

      - name: upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tbd_firmware_${{ inputs.tbd-platform }}
          path: |
            build/${{ inputs.tbd-platform }}/tbd-${{ inputs.tbd-platform }}-flash.bin
          overwrite: true
