name: tbd-sim-tapp-osx

on:
  push:
    branches:
      - osx
  pull_request:
    branches:
      - osx

jobs:
  build:

    runs-on: macos-latest

    steps:
      - run: brew install boost
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cd tapp && mkdir build && cd build && cmake .. && make && cpack && cd ../..
      - run: cd simulator && mkdir build && cd build && cmake .. && make && cpack && cd ../..
      - name: Archive binaries
        run: |
          zip --junk-paths binaries tapp/build/*.zip simulator/build/*.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: tbd-sim-tapp-osx-${{ github.sha }}
          body: |
            tapp osx
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./binaries.zip
          asset_name: binaries.zip
          asset_content_type: application/zip